
version: "3"
services:
  moontrek-server:
    build:
      context: server/
    image: moontrek-server
    container_name: moontrek-server
    restart: unless-stopped
    volumes:
      - "./data/server/config:/src/config"
      - "./data/server:/src/data"
    ports:
      - "8888:8888"
  
  moontrek-python-server:
    build:
      context: python-server/
      args:
        MR_ENABLE_OPENCV_NONFREE: ${MR_ENABLE_OPENCV_NONFREE}
    image: moontrek-python-server
    container_name: moontrek-python-server
    restart: unless-stopped
    volumes:
      - "./data/python-server/config:/app/config"
      - "./data/python-server:/app/data"
    ports:
      - "5000:5000"
  
  moontrek-client:
    build:
      context: client/
      args:
        BACKEND_SERVER: ${BACKEND_SERVER}
        PYTHON_SERVER: ${PYTHON_SERVER}
        MR_ENABLE_OPENCV_NONFREE: ${MR_ENABLE_OPENCV_NONFREE}
    image: moontrek-client
    container_name: moontrek-client
    restart: unless-stopped
    ports:
      - "5173:5173"
